version: '3'
services:
  db:
    image: postgres
    ports:
      - "8000:5432"
  web:
    build: .
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
