version: '3'
services:
  db:
    image: postgres
    env_file: .env
    ports:
      - "8000:5432"
  web:
    build: .
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
